### ISSUE TITLE
Have Mosquito Broker on Hassio, unsure of the settings required to connect HassBridge

### ISSUE THREAD

**Issue by EagleDTW** [wonderslug/hassbridge#13]
Hi Wonderslug,

Have Mosquito Broker on Hassio installed and running, unsure of the settings required to connect HassBridge - I don't know how to configure the name and word for the server or the exact settings for the communication - would you please elaborate for how to setup using the config and where to gather these identifiers?

I either get error8 nodename nor server name identified, or connection timeout as SSL connection refused - and I'm sure it's my naivity, but I'm not sure how to configure. I played around some more and have resolved ssl issues but now get error54 connection refused from the MQTT broker, any ideas?

Thank you,
Daniel

**Comment by wonderslug** [comment]
Howdy Daniel

You should be able to really simply setup your Mosquito if your on Hassio.

From the HassBridge standpoint it should be very simple.  Point the server address to your hassio server. choose the protocol you want and if you have SSL.  Enter your username and password you setup in the Mosquito config.

Can you post your edited Mosquito config here without the password for the users so we can see if there is anything odd?

-=Brian

**Comment by EagleDTW** [comment]
Hi Brian,

That’s what I was thinking. Below config.yaml:
mqtt:
 broker: 192.168.x.xx
 port: 1883
 username: edited_out
 password: edited_out

Don’t know if the refusal by the MQTT broker is due to misconfigured Indigo setting...found that I’m not using ssl to the server and that fixed connection, but I selected the items in the picker below for devices and variables- and nothing is coming up in HassIO, am I missing another step?

Thank you,
Daniel

**Comment by EagleDTW** [comment]
Added discovery: true and I’m up and running, thank you Brian! Really useful plugin and integration!
