### ISSUE TITLE
Changing "Event Name Prefix:" or "Home Assistant Discovery Prefix:" has no effect

### ISSUE THREAD

**Issue by Hackencrash** [wonderslug/hassbridge#2]
Cut and paste from Indigo event log (Debug on v0.4.0)

HassBridge Error                Exception trapped:generate() takes exactly 3 arguments (4 given)
   HassBridge Error                Error in plugin execution UiClosed1:

Traceback (most recent call last):
  File "plugin.py", line 145, in closedPrefsConfigUi
  File "plugin.py", line 127, in update_perfs
  File "plugin.py", line 342, in _setup_ha_devices
  File "plugin.py", line 396, in _remap_ha_devices
TypeError: generate() takes exactly 3 arguments (4 given)

**Comment by wonderslug** [comment]
Howdy,

Thanks for the bug report.

Looks like the bug from the traceback is a simple one to fix and affects only the use of indigo variables as sensors.   A fix will be out in the next release shortly.

Ive verified the Event Name Prefix and Home Assistant Discovery Prefix are both working as exepected.

The Event Name Prefix changes the prefix of the event name sent to Home Assistant.  This can be verified by watching Home Assistant events in the developer tools on your Home Assistant install.

The Home Assistant Discovery Prefix modifies the Discovery Prefix the MQTT topics are created under for Home Assistant to pick up.  It needs to match the prefix defined in the Home Assistant Setup for MQTT discovery.  Unless those two match you wont see any effect.

**Comment by wonderslug** [comment]
Please let me know if there is still an issue and reopen.   Thanks

**Comment by Hackencrash** [comment]
Will do

Thank you

Richard Lailey
07973 264888

On 23 Apr 2020, at 05:44, Brian Towles <notifications@github.com> wrote:

﻿

Please let me know if there is still an issue and reopen. Thanks
